### ISSUE TITLE
Would be nice addition to FoxTypes

### ISSUE THREAD

**Issue by eselje** [atlopes/UTCDatetime#1]
There's a project called FoxTypes I worked on to extend the String, Date, and Array types to be more like .Net static types. Some of these features are already in there, but I may steal the other ones too! Nice work.

**Comment by atlopes** [comment]
Thank you, Eric.

I know of FoxTypes, and it would be interesting to see UTCDatetime (which is, on its own, an application of iCal4VFP) being reused in the context  I'll be happy to assist if needed.
